### ISSUE TITLE
Make a web service for the CLI tool

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/waiting-time-backend#1]
# User Story

As a user, 
I want to use the tool as a web service, 
so that I don't need to install and maintain it on my own. 

# Acceptance criteria

## FR

(Most requirements are defined in the API specification)

- [x] Job queue is required to handle multiple user job requests
- [x] CLI tool result as JSON
- [x] Web service should store the processing results and serve the output files to the user on request
- [x] Packaged as a Docker image
- [x] Deployment to production environment
- [x] Do not submit the same job twice for processing (check by event log name and content hash)
- [x] Ability to cancel a long running job by a user, so we don't waste computing resources
- [x] Accept an event log through an API's request body
- [x] Accept an event log from URL
- [x] Call the callback endpoint on job done
- [x] Empty queue: (a) one time on request, (b) periodic
- [x] File storage should be limited in size, if the limit is reached, older job results are removed

## NFR

- [x] Public API specification

**Comment by JonasBerx** [comment]
Another note, I'm having issues with CORS. Any chance that could be server related?



--- Disregard below, figured that out

Hey,
I have a quick question:

Can you provide me with an example requestbody? I'm a bit confused what you mean with event_log being the URL to the log file. Does it mean that you want me to send you a URL where the backend would download the csv and process the job or should the event_log parameter contain the .csv file in the body?

At this moment my requestbody looks something like this.

{
event_log: [{obj1}, {obj2}, ... {obj n}],
callback_endpoint: "somecallbackurl"
}

**Comment by iharsuvorau** [comment]
> Hey, I have a quick question:
> 
> Can you provide me with an example requestbody? I'm a bit confused what you mean with event_log being the URL to the log file. Does it mean that you want me to send you a URL where the backend would download the csv and process the job or should the event_log parameter contain the .csv file in the body?
> 
> At this moment my requestbody looks something like this.
> 
> { event_log: [{obj1}, {obj2}, ... {obj n}], callback_endpoint: "somecallbackurl" }

@JonasBerx Hey, no problem. Here's how it's implemented at the moment:

```json
{
  "event_log": "http://localhost:8090/assets/samples/PurchasingExample.csv",
  "callback_endpoint": "http://example.com/callback"
}
```

I'm serving one sample log with the server, so we can test our services. The event log can be hundred of megabytes. In theory, it's unlimited. So, I propose to just give an URL of the log, so the backend service can download it when it's time for the job.

The response on the request above is the following for now:

```json
{
  "id": "2537363a-02a1-11ed-8748-7e18b86c7993",
  "status": "pending",
  "callback_endpoint": "http://example.com/callback",
  "event_log": "http://localhost:8090/assets/samples/PurchasingExample.csv",
  "created_at": "2022-07-13T14:44:25.571965+03:00"
}
```

If the error is there, the response is:

```json
{
  "id": "2537363a-02a1-11ed-8748-7e18b86c7993",
  "status": "failed",
  "error": "reason of failure",
  "callback_endpoint": "http://example.com/callback",
  "event_log": "http://localhost:8090/assets/samples/PurchasingExample.csv",
  "created_at": "2022-07-13T14:44:25.571965+03:00",
  "finished_at": "2022-07-13T14:46:49.83176+03:00"
}
```

It's a bit different from the API Specification, I'll update the specification when finish the implementation.

When the job is completed, the response would just include more attributes:

```json
{
  "id": "2537363a-02a1-11ed-8748-7e18b86c7993",
  "status": "completed",   
  "report_csv": "http://localhost:8090/assets/results/2537363a-02a1-11ed-8748-7e18b86c7993/PurchasingExample_handoff.csv",
  "callback_endpoint": "http://example.com/callback",
  "event_log": "http://localhost:8090/assets/samples/PurchasingExample.csv",
  "created_at": "2022-07-13T14:44:25.571965+03:00",
  "finished_at": "2022-07-13T14:46:49.83176+03:00"
}
```

So far, the following endpoints are implemented:

Action | Endpoint | Description
-------|----------|------------
POST | http://localhost:8090/jobs | Submit a job. A body is required.
GET | http://localhost:8090/jobs | Get all the jobs. (Not sure if we expose this to the public, because event logs might be private and sensitive)
GET | http://localhost:8090/jobs/{id} | Job's data.

**Comment by iharsuvorau** [comment]
> Another note, I'm having issues with CORS. Any chance that could be server related?

@JonasBerx It is. But what do you use as a server at the moment? I need to allow access to backend endpoints from other domains.

**Comment by JonasBerx** [comment]
> > Another note, I'm having issues with CORS. Any chance that could be server related?
> 
> @JonasBerx It is. But what do you use as a server at the moment? I need to allow access to backend endpoints from other domains.

I'm just executing main.go locally.

**Comment by iharsuvorau** [comment]
> > > Another note, I'm having issues with CORS. Any chance that could be server related?
> > 
> > 
> > @JonasBerx It is. But what do you use as a server at the moment? I need to allow access to backend endpoints from other domains.
> 
> I'm just executing main.go locally.

Oh, you're already in the code. Yes, I forgot about CORS. I'll add it now and then finish with making it public.

**Comment by iharsuvorau** [comment]
@JonasBerx Pushed CORS changes. Does it work now?

**Comment by JonasBerx** [comment]
@iharsuvorau In Postman the request passes, on react server the request is still blocked. 
![image](https://user-images.githubusercontent.com/43341402/178761563-8361036f-621e-44a9-a4ef-21a28dd2535b.png)

**Comment by iharsuvorau** [comment]
> @iharsuvorau In Postman the request passes, on react server the request is still blocked.
> ![image](https://user-images.githubusercontent.com/43341402/178761563-8361036f-621e-44a9-a4ef-21a28dd2535b.png)

@JonasBerx What about now? I didn't serve the OPTIONS method of HTTP that clients usually use.

**Comment by JonasBerx** [comment]
> > @iharsuvorau In Postman the request passes, on react server the request is still blocked.
> 
> > ![image](https://user-images.githubusercontent.com/43341402/178761563-8361036f-621e-44a9-a4ef-21a28dd2535b.png)
> 
> 
> 
> @JonasBerx What about now? I didn't serve the OPTIONS method of HTTP that clients usually use.

Yep! Went through, thx a lot!

**Comment by iharsuvorau** [comment]
@JonasBerx You can now take the binary from each GitHub Actions workflow run instead of running it from source. Here's an example workflow: https://github.com/AutomatedProcessImprovement/waiting-time-backend/actions/runs/2664403179. There's the `Artifacts` section at the bottom of the page.

**Comment by JonasBerx** [comment]
Hey,

I suppose this is an issue with my machine running windows. If i understand the error correctly it just means that it cant find the sh command in windows cmd? 
````
{"job":{"id":"eb80a231-0342-11ed-b7d7-fc34974ac7f4",
"status":"failed",`
"error":"exec: \"sh\": executable file not found in %PATH%",
"callback_endpoint":"http://example.com/callback",
"event_log":"http://localhost:8080/assets/samples/PurchasingExample.csv",
"created_at":"2022-07-14T10:02:27.2154161+03:00",
"finished_at":"2022-07-14T10:02:29.1723593+03:00"}}

**Comment by iharsuvorau** [comment]
> Hey,
> 
> I suppose this is an issue with my machine running windows. If i understand the error correctly it just means that it cant find the sh command in windows cmd?
> 
> ```
> {"job":{"id":"eb80a231-0342-11ed-b7d7-fc34974ac7f4",
> "status":"failed",`
> "error":"exec: \"sh\": executable file not found in %PATH%",
> "callback_endpoint":"http://example.com/callback",
> "event_log":"http://localhost:8080/assets/samples/PurchasingExample.csv",
> "created_at":"2022-07-14T10:02:27.2154161+03:00",
> "finished_at":"2022-07-14T10:02:29.1723593+03:00"}}
> ```

@JonasBerx Oh, yeah. I'm packaging the web server together with Python CLI into a Docker image now. Then we can forget about running binaries of the web server under different OS, everything will be from the same Docker container with Linux.

**Comment by iharsuvorau** [comment]
@JonasBerx Hey, few changes here:

- Docker image is publicly accessible via `docker pull nokal/waiting-time-backend`.
- Public server is up at http://193.40.11.233. You can see all the jobs at http://193.40.11.233/jobs. It has few computing resources at the moment.

So, you can try using the last option for your development as it should be the easiest, but in case you want to see backend logs, then you can try via Docker on your own.

**Comment by iharsuvorau** [comment]
@JonasBerx Hey, I've updated the web service which now returns all the data. I'm still verifying if the calculations are correct, but all the fields are there. You can see an example at http://193.40.11.233/jobs/9b3b010c-08e7-11ed-b405-0242ac110002

**Comment by iharsuvorau** [comment]
@JonasBerx Wait a sec, I'm renaming some fields, so they correspond to what David has sent to us

**Comment by iharsuvorau** [comment]
@JonasBerx Updated, here's it http://193.40.11.233/jobs/2d7261f0-08f4-11ed-90e9-0242ac110002

**Comment by JonasBerx** [comment]
@iharsuvorau Is the server down by any chance? Connection gets refused

**Comment by iharsuvorau** [comment]
@JonasBerx Yes, it is. I'm switching to Docker Compose, but it's not so quick. The default version is old. Upgrading...

**Comment by JonasBerx** [comment]
Oki, no worries!

**Comment by iharsuvorau** [comment]
@JonasBerx Alive now. I'll be restarting it today more than usual, but it should take now only seconds to restart.

**Comment by iharsuvorau** [comment]
@JonasBerx There're some changes in responses. 

- I removed the "job" key when returning a single job from `GET /jobs/{id}` and from `POST /jobs`
    ```json
    {
        "id": "45966fdf-09d1-11ed-95fe-0242c0a85002",
        "status": "pending",
        "callback_endpoint": "http://example.com/callback",
        "event_log": "http://193.40.11.233/assets/samples/manual_log_5.csv",
        "created_at": "2022-07-22T18:16:33.86575522+03:00"
    }
    ```
- If there's an error, the response would be just an object with `error` string field.
    ```json
    {
        "error": "job with id c00f10d1-09b2-11ed-9ed6-0242ac1d0002 not found"
    }
    ```

Specification is now published at http://193.40.11.233/api/.

**Comment by iharsuvorau** [comment]
@JonasBerx `POST /jobs` can now accept an event log in the request body. Here's a `curl` request example:

```
curl --location --request POST 'http://193.40.11.233/jobs' \
--header 'Content-Type: text/csv' \
--data-binary '@/path/to/log/event_log.csv'
```

It's important to set up `Content-Type: text/csv`, because that's how the type of the request body is identified.

**Comment by JonasBerx** [comment]
@iharsuvorau 
Hey,

I'm running into an issue with posting a new job.
Not sure what is causing it..

~
`{"id":"71e02868-0bf2-11ed-9592-0242c0a87002","status":"failed","error":"exit status 1","event_log":"http://193.40.11.233/assets/results/71e02868-0bf2-11ed-9592-0242c0a87002/event_log.csv","event_log_md5":"2c360084d1bc655b6ae0d7e17356b751","created_at":"2022-07-25T11:19:03.886381128+03:00","finished_at":"2022-07-25T11:19:08.999751084+03:00"}]}`
~

The request header should be set up correctly:

POST
HEADER: "Content-Type: text/csv"
{
event_log: "path/to/event/log.csv",
callback_endpoint: "http://example.com/callback",
}

**Comment by iharsuvorau** [comment]
@JonasBerx Hi, headers are correct, the body is incorrect. The content of the body should be the event log itself in binary, no JSON should be provided if you use `text/csv` as a content type.

When I check the event log that have been decoded from your request, I see the following:
```shell
$ cat assets/results/71e02868-0bf2-11ed-9592-0242c0a87002/event_log.csv
{"event_log":{"path":"20linetestdata.csv"},"callback_endpoint":"http://example.com/callback"}
```

Which means, JSON was sent as CSV, so I saved JSON as an event log and the CLI tool crashed trying to read it. I agree error messages need to be improved though :)

If you use Postman, you can encode CSV into the request body by specifying "Body" -> "binary". 

<img width="1392" alt="Screenshot 2022-07-25 at 12 39 23" src="https://user-images.githubusercontent.com/6259054/180747472-b9848f06-e778-44c8-97d8-3a97f9d0e367.png">

With curl, you can do

```
curl --location --request POST 'http://193.40.11.233/jobs' \
--header 'Content-Type: text/csv' \
--data-binary '@/20linetestdata.csv'
```

**Comment by JonasBerx** [comment]
@iharsuvorau 
I should have asked this before.
The names of the header of each column in your files are different than the csv files I was using. This also caused parsing crashes I think.
Regardless, issues are resolved now :)

**Comment by iharsuvorau** [comment]
@JonasBerx Hi, there're some updates deployed.

- CTE calculations updated
  - Global CTE impact now moved inside the report
  - Transition level CTE impact added
  - process_cte field added
  - total_pt field added
- DELETE /jobs endpoint added. It removes all the data. It's useful for debugging, because when I need to recalculate the same log with new fields added, the server treats a job as a duplicate and does nothing. I'll hide it later under a password
- API specification is updated. See "Models → JobResult" at http://193.40.11.233/api/

**Comment by iharsuvorau** [comment]
@JonasBerx One more update:

- CTE impact per resource transition added too. See http://193.40.11.233/jobs/41aab615-0e85-11ed-bf59-0242c0a8c002 as an example

Backend should have now all the data available.

**Comment by iharsuvorau** [comment]
Hi @JonasBerx. A couple of updates:

- Calling the callback endpoint is implemented now in case you need it. You don't if you use event log uploading via a request body though.
- Jobs older than 1 month are periodically removed now.

I'm closing this mega-issue now. If you found or need something else, please, feel free to open a new issue.

**Comment by JonasBerx** [comment]
@iharsuvorau
Thanks a lot! Have a nice holiday!
