### ISSUE TITLE
Include processing time vs waiting time per case data into the response

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/waiting-time-backend#2]
See https://github.com/AutomatedProcessImprovement/waiting-time-analysis/issues/33

**Comment by iharsuvorau** [comment]
Hi @JonasBerx. I'm back since today. In office on Thu-Fri. Here's the issue related to the new table with processing and waiting time data per case. The production server has been just updated. Here's the sample output: http://193.40.11.233/jobs/10bd102d-1e36-11ed-a767-0242c0a8e002. The new data is located at `response > result > per_case_wt`.

**Comment by JonasBerx** [comment]
Hey @iharsuvorau 
Great! Another feature that should be implemented that Katsiaryna and I discussed is the ability for the server to accept a log mapping in json format like the following segment:
```
{
case_id : name_of_row_in_csv_that_corresponds_to_case_id,
activity: name_of_row_in_csv_that_corresponds_to_activity,
start_timestamp: name_of_row_in_csv_that_corresponds_to_start_time,
...
}
```

We could discuss this tomorrow if you're in the office as I think this might require some rework the formation of the request.
