### ISSUE TITLE
Column mapping for event log

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/waiting-time-backend#3]
See https://github.com/AutomatedProcessImprovement/waiting-time-analysis/issues/34 for more details. Ensure it's supported on the backend too.

**Comment by iharsuvorau** [comment]
@JonasBerx Hi, here's the issue related to column mapping. It has been implemented for `POST /jobs` for 2 content types, JSON and CSV. 

For content-type JSON, the following body should be provided:

```json
{
    "event_log": "http://localhost:8080/assets/samples/manual_log_5.csv", 
    "callback_endpoint": "http://example.com/callback",
    "column_mapping": {
        "case": "case:concept:name",
    }
}
```

For content-type CSV, the mapping goes into the URL's path:

`POST http://193.40.11.233/jobs?case=case_id&activity=activity&resource=resource&start_timestamp=start_timestamp&end_timestamp=end_timestamp`

Only the following keys are supported:

- case
- activity
- resource
- start_timestamp
- end_timestamp

**Comment by JonasBerx** [comment]
Hey @iharsuvorau 

I think this is a small bug on your end.
In 'per_case_wt' all case ids are 0. this probably has to do with the mapping not being translated correctly to the tool. rest all works as expected

```"per_case_wt":[{"case:concept:name":0,"pt_total":4200,"wt_total":6300,"cte_impact":0.4},{"case:concept:name":0,"pt_total":4440,"wt_total":9000,"cte_impact":0.33035714285714285},{"case:concept:name":0,"pt_total":4800,"wt_total":6300,"cte_impact":0.43243243243243246},{"case:concept:name":0,"pt_total":4620,"wt_total":9600,"cte_impact":0.32489451476793246},{"case:concept:name":0,"pt_total":8880,"wt_total":1800,"cte_impact":0.8314606741573034},{"case:concept:name":0,"pt_total":4200,"wt_total":6300,"cte_impact":0.4},{"case:concept:name":0,"pt_total":4440,"wt_total":9000,"cte_impact":0.33035714285714285},{"case:concept:name":0,"pt_total":4800,"wt_total":6300,"cte_impact":0.43243243243243246},{"case:concept:name":0,"pt_total":4620,"wt_total":9600,"cte_impact":0.32489451476793246},{"case:concept:name":0,"pt_total":8880,"wt_total":1800,"cte_impact":0.8314606741573034},{"case:concept:name":0,"pt_total":4200,"wt_total":6300,"cte_impact":0.4},{"case:concept:name":0,"pt_total":4440,"wt_total":9000,"cte_impact":0.33035714285714285},{"case:concept:name":0,"pt_total":4800,"wt_total":6300,"cte_impact":0.43243243243243246},{"case:concept:name":0,"pt_total":4620,"wt_total":9600,"cte_impact":0.32489451476793246},{"case:concept:name":0,"pt_total":8880,"wt_total":1800,"cte_impact":0.8314606741573034}]}```

**Comment by iharsuvorau** [comment]
@JonasBerx Thanks for debugging. Working on it. 

I wouldn't apply column mapping for outputting data in the next update. The "per_case_wt" array would have objects with the same keys independent of the column mapping for event log. All stays the same in the API response except "case:concept:name" is renamed to "case_id". In 30+ min, all Docker images should be built and updated.

**Comment by iharsuvorau** [comment]
@JonasBerx It is updated now. Seems okay, http://193.40.11.233/jobs/7ac21658-1fae-11ed-969c-0242ac120002.

**Comment by JonasBerx** [comment]
Hey @iharsuvorau

Bit of a late update; 
I'm a little confused where this error is coming from 
```
"error":"error reading result: invalid character 'N' looking for beginning of value"
```

This error happens when i have the following column names:
![image](https://user-images.githubusercontent.com/43341402/185699438-289c7fac-865a-4aed-9d41-f40ec9cfb5d2.png)

However when i use names like:
![image](https://user-images.githubusercontent.com/43341402/185699509-cc4bfa6c-f084-448a-8d72-0083eb491e14.png)

There are no issues with the processing.
I think this could have to do with the fact that there are uppercase characters but other than that I have no clue.

**Comment by iharsuvorau** [comment]
@JonasBerx Hi, okay, thanks. I'm looking into it today.

**Comment by iharsuvorau** [comment]
@JonasBerx It should be fixed now. I used the column mapping where I shouldn't have to in the final report. Please, check it again.

http://193.40.11.233/jobs/a4247822-239b-11ed-98f8-0242ac140002
